project_id = "qbaxmdmxpmnzbuagzatn"

[functions.analyze-conversation]
verify_jwt = false

[functions.generate-sora-video]
verify_jwt = false

[functions.download-sora-video]
verify_jwt = false

[functions.convert-to-gif]
verify_jwt = false

[functions.proxy-image-search]
verify_jwt = false
